name: ðŸš€ Deploy Release

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy Release ðŸŸ¢
        uses: devuri/plugin-release-deploy-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          php-version: '8.1'
          plugin-slug: 'basic-plugin'
          build-dir: './build/basic-plugin/'
          zip-file: './build/basic-plugin.zip'
          svn-username: ${{ secrets.WP_SVN_USERNAME }}
          svn-password: ${{ secrets.WP_SVN_PASSWORD }}
